const BrainstormingTypes = {
    LOAD_SUBJECTS: "LOAD_SUBJECTS",
    CHANGE_CURRENT_SUBJECT: "CHANGE_CURRENT_SUBJECT",
    LOAD_MESSAGES: "LOAD_MESSAGES",
    UPDATE_SUBJECT: "UPDATE_SUBJECT",
    SET_LOADING: "SET_LOADING"
}

export default BrainstormingTypes;