const ModalTypes = {
    TOGGLE_CREATE_BRAINSTORMING: 'TOGGLE_CREATE_BRAINSTORMING',
    TOGGLE_SEND_MESSAGE: 'TOGGLE_SEND_MESSAGE',
    TOGGLE_PORTFOLIO_MODAL: 'TOGGLE_PORTFOLIO_MODAL',
    TOGGLE_NOTES_MODAL: 'TOGGLE_NOTES_MODAL',
    TOGGLE_NOTES_MODIFY: 'TOGGLE_NOTES_MODIFY',
    TOGGLE_PORTFOLIO_MODIFY: 'TOGGLE_PORTFOLIO_MODIFY'
}

export default ModalTypes;